<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  0 => '',
  'Comment by the Administration: ' => '',
  'Group deleted ' => '',
  'Handling administration blocked due to a violation of the rules {tag}site{/tag}.' => '',
  'Occasion administration is locked due to violation of rules {tag}site{/tag}.' => '',
  'Survey administration blocked due to a violation of the rules {tag}site{/tag}.' => '',
  'URL blocked by a moderator because of a violation of the rules {tag}site{/tag}' => '',
  '{profile} deleted share &laquo;{name}&raquo;.' => '',
  '{profile} has removed the action &laquo;{name}&raquo;.' => '',
  '{profile} has removed the action.' => '',
  '{profile} removed the action.' => '',
  'The action was blocked by the administration.' => 'La acción se bloqueó por la administración.',
  'The activity of the profile {pronoun} is suspended according to {tag}the website rules{/tag}.' => 'La actividad del perfil {pronoun} está temporalmente suspendida según {tag}las reglas del sitio{/tag}.',
  'The event is blocked by the administration due to the {tag}site`s rules{/tag} violation.' => 'El evento está bloqueado por la administración a causa de violación de las {tag}reglas del sitio{/tag}.',
  '{profile} deleted the event &laquo;{name}&raquo;.' => '{profile} eliminó el evento &laquo;{name}&raquo;.',
  '{profile} deleted the issue &laquo;{name}&raquo;.' => '{profile} eliminó el asunto &laquo;{name}&raquo;.',
  '{profile} deleted the link &laquo;{name}&raquo;.' => '{profile} eliminó el enlace &laquo;{name}&raquo;.',
  '{profile} deleted the poll &laquo;{name}&raquo;.' => '{profile} eliminó la votación &laquo;{name}&raquo;.',
);
