<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  0 => '',
  '- Create groups and participate in {br /}' => '',
  '- To collect and give money to socially useful projects and actions {br /} ' => '',
  '- To create excuses, handling, voting events {br /}' => '',
  'After confirmation, you will discover many new features on {siteName}. You`ll be able to: {br /}' => '',
  'After confirmation, you will discover many new features to the project {siteName} ' => '',
  'Code is in SMS' => '',
  'Confirm your phone number' => '',
  'Confirmation code ' => '',
  'Do you really want to make this account primary? ' => '',
  'Image size not more than 5MB. ' => '',
  'No, thanks' => '',
  'Select the account under which you want to use {siteName}' => '',
  'Send confirmation code' => '',
  'There was an error loading the image. ' => '',
  'You are logged in as' => '',
  'Your profile picture' => '',
  ' - social initiative support platform' => ' - plataforma de apoyo de inciativas sociales',
  ' The file extension jpg | jpeg | png | tiff | gif.' => ' Formato del archivo jpg | jpeg | png | tiff | gif',
  ' develops a participatory society, involving locals in changing what`s around them. The platform helps to make life better in a particular courtyard, district and a whole city.' => ' desarrolla una sociedad de participación, que incluye los residentes en la transformación del ambiente. La plataforma ayuda a mejorar la vida en un patio, barrio concreto o en toda la ciudad.',
  'A server error occurred, please try later.' => 'Un error del servidor ocurrió, por favor intente más tarde.',
  'Add' => 'Añadir',
  'Cancel' => 'Cancelar',
  'Change the password' => 'Cambiar la contraseña',
  'Create an account' => 'Crear una cuenta',
  'Enter the e-mail address provided during the registration, and press "Change the Password". We’ll send you a new password.' => 'Introduzca el correo electrónico usado durante el registro y pulse “Cambiar la contraseña”. Le enviaremos la nueva contraseña.',
  'False' => 'No',
  'I accept {userAgreementLink}the terms of use{/userAgreementLink}, agree with processing my personal data and confirm that I am 18.' => 'Acepto las {userAgreementLink}condiciones de uso{/userAgreementLink}, consiento el tratamiento de mis datos personales.',
  'Inhabited locality`s name' => 'Nombre de la localidad',
  'Log in' => 'Iniciar sesión',
  'Log out' => 'Salida',
  'Or sign in through your social network profile' => 'O entre a través de su perfil en redes sociales',
  'Registration' => 'Registro',
  'Remember' => 'Recordar',
  'Reset the password with a phone number' => 'Recuperar la contraseña por el número de teléfono',
  'Settings' => 'Ajustes',
  'True' => 'Cierto',
  'Upload another photo' => 'Cargar otra foto',
  'Yes' => 'Sí',
  'Your e-mail address' => 'Su correo electrónico',
  'Your e-mail address or phone number' => 'Su correo electrónico o número de teléfono',
  'Your name' => 'Su nombre',
  'Your password' => 'Su contraseña',
  'Your phone number' => 'Su número de teléfono',
  'Your surname' => 'Su apellido',
  'add' => 'añadir',
  'confirm' => 'confirmar',
  'done' => 'hecho',
  'log in' => 'iniciar sesión',
  'save' => 'guardar',
  'Continue' => 'Continuar',
);
