<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'City: ' => '',
  'Contact phone: ' => '',
  'Lock business profile on {siteName} ' => '',
  '"{name} ({link})" profile`s administrator designated you as {position}.' => 'El administrador del perfil "{name} ({link})" le designó {position}.',
  'E-mail: ' => 'Correo electrónico: ',
  'If you have questions or proposals, contact us: {support_email}
This letter was sent automatically, don`t reply. ' => 'Si tiene preguntas o propuestas, póngase en contacto con nosotros: {support_email}
Esta carta se envió automaticamente, no la responda. ',
  'Kind regards, ' => 'Atentamente, ',
  'Name: ' => 'Nombre: ',
  'Show more' => 'Mostrar más',
  'Subscribe' => 'Suscribirse',
  'Unsubscribe' => 'Cancelar',
  'Volunteer`s questionnaire on {siteName}' => 'Cuestionario del voluntario en {siteName}',
  '{siteName}: you are listed as "{businessprofile}" employee' => '{siteName}: notificaión sobre la suscripción al perfil de negocio "{businessprofile}"',
);
