<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'A server error occurred. Try again later.' => '¡Huy! Un error de servidor. Inténtelo de nuevo más tarde.',
  'Close the promo pack and not show it in the profile.' => 'Cerrar el promo pack y no mostrarlo en el perfil.',
  'Edit' => 'Editar',
  'Oops! The photo should be not smaller than 800x600 and not smaller than 15Mb. File`s format: jpg | jpeg | png | tiff | gif.' => '¡Huy! La foto debe ser no menos de 800x600 y no más de 15Mb. El formato del archivo: jpg | jpeg | png | tiff | gif.',
  'The photo should be not smaller than 800x600 and not smaller than 15Mb.' => 'La foto debe ser no menos de 800x600 y no más de 15Mb.',
  'Upload a background image' => 'Cargar un imagen de fondo',
  'Upload another photo (not bigger than 15 MB, not smaller than 800x600).' => 'Cargar otra foto (no más de 15 Mb, no menos de 800x600).',
  'cancel' => 'cancelar',
  'open the promo pack' => 'abrir el promo pack',
  'save' => 'guardar',
  'upload your' => 'Cargar la suya',
);
