<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Your contribution to {siteName} has received a new comment' => 'Tu contribución en {siteName} ha recibido un comentario nuevo',
  'comment deleted' => '',
  ' ' => ' ',
  'COMMENTS' => 'COMENTARIOS',
  'Cancel' => 'Cancelar',
  'Comment' => 'Сomentario',
  'Reply' => 'Responder',
  'Save' => 'Guardar',
  'You have an answer to your comment on {siteName} ' => 'Tienes una respuesta a tu comentario en {siteName}',
  'all comments' => 'todos los comentarios',
  'commented on' => 'comentó',
  'comment|comments' => 'comentario|comentarios',
  'on' => 'en',
  'replied' => 'respondió',
  'to your comment in' => 'a tu comentario de',
  'userpic' => 'imagen de perfil',
  '{n} answer|{n} answers|{n} answers' => '{n} respuesta|{n} respuestas|{n} respuestas',
  'Delete this comment' => 'Eliminar comentario',
  'Hide the comment' => 'Ocultar comentario',
  'Moderate the comment' => 'Moderar comentario',
  'Revert Comment Moderation' => 'Desmoderar comentario',
  'Moderated Comment' => 'Comentario Moderado',
);
