<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Edit Poll ' => '',
  'Edit appeal ' => '',
  'Edit event ' => '',
  'Edit link' => '',
  'Edit pretext ' => '',
  'Mode ' => '',
  'Through fasting ID ' => '',
  'Comments' => 'Сomentarios',
  'Creation date' => 'Fecha de creación',
  'Edit the action' => 'Editar la acción',
  'Edit the profile' => 'Editar el perfil',
  'Group ' => 'Grupo',
  'Latitude' => 'Latitud',
  'Life sphere' => 'Esfera de vida',
  'Longitude' => 'Longitud',
  'Organization' => 'Organización',
  'Region' => 'Región',
  'Status' => 'Estado',
  'Status in the group' => 'Estado en el grupo',
  'Supplementary status in the group' => 'Estado adicional en el grupo',
  'User' => 'Usuario',
  'Venue' => 'Lugar',
);
