<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Anonymous user' => '',
  'To register, click on "Give money"' => '',
  'collected' => '',
  'collected of {n}' => '',
  'Donation period' => 'Período de recolección de donaciones',
  'Sponsorship campaign is over<br />The target sum wasn`t collected' => 'La campaña de patrocinio ha finalizado<br />La suma no se colectó',
  'The donated amount will leave your account each month during the donation period' => 'La cantidad de la donación deducirá de su cuenta cada mes durante el período de la donación',
  'The donated sum will be lodged in your account each month for during the donation period' => 'La cantidad de la donación se colocará en su cuenta cada mes durante el período de la donación',
  'After fulfillment of your promise,{br /}share the results with everyone' => 'Después del cumplimiento de la promesa, cuente a todo el mundo {br /} sobre el proceso y sus resultados',
  'Choose an action' => 'Elejir una acción',
  'Crowdfunding is finished' => 'Crowdfunding se acabó',
  'Crowdfunding is over<br>The target sum wasn`t collected' => 'Crowdfunding se acabó<br>La suma no se colectó',
  'Donate' => 'Donar',
  'It`s done!' => 'Hecho!',
  'The action is canceled' => 'La acción está cancelada',
  'The action<br /> is failed' => 'La acción <br /> se acabó',
  'The action<br /> is stopped.' => 'La acción <br /> se paró.',
  'The organizator will have {n} days to use the money by purpose.' => 'El organizador tendrá {n} días para usar el dimero por objetivo previsto',
  'The promise <br /> is fulfilled' => 'La promesa  <br /> se cumplió',
  'The promise <br /> isn`t fulfilled' => 'La promesa <br /> no se cumplió',
  'The report template with further instructionswill be sent to your{tag}{email}{/tag}.' => 'El forma del reporte y las instrucciones siguientes se enviarán a su correo eléctronio {tag}{email}{/tag}.',
  'The time for fulfillment has passed{br /}The promise wasn`t fulfilled' => 'El plazo expiró{br /}La promesa no se cumplió',
  'Time for fulfillment' => 'Se queda para la realización',
  'Time for fulfillment has passed. Nothing is done.' => 'El plazo expiró. Nada está hecho.',
  'To choose an action you have' => 'Para elegir la acción ',
  'Until the end' => 'Hasta la terminación',
  'Yay! The money is collected!' => '¡Guay! ¡El dinero se colectó!',
  'You donated ' => 'Donó ',
  'You transferred to the action' => 'Transferió a la acción',
  'You`ll have {n} days to use the money by purpose' => 'Tendrá {n} días para usar el dinero por objetivo previsto',
  'collected {collected}' => 'recogido {collected}',
  'or you can {tag}cancel the action{/tag}' => 'o usted podrá {tag}cancelar la acción{/tag}',
  'reports' => 'reportes',
  'the action didn`t raise enough funds, but you can transfer your money to other action.' => 'la acción no recogió bastante dinero, pero puede transferir su dinero a otra acción.',
  'until the end' => 'hasta la terminación',
  'you donated ' => 'donó ',
  'your supporters are waiting! fulfill your promises and share the story!' => 'la gente espera al cumplimiento de la promesa. hágalo y cuente a todo el mundo',
  '{n} days left' => '{n} días se quedan',
  '{n} person | {n} people' => '{n} personas',
  '{n}day left |{n} days left | {n} days left ' => '{n} día se queda |{n} días se quedan | {n} días se quedan ',
  '{tag}{collected}{/tag} out of {total}' => '{tag}{collected}{/tag} de {total}',
  '{tag}{collected}{/tag}{br /} collected' => '{tag}{collected}{/tag}{br /} recogido',
);
