<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' The file extension jpg | jpeg | png | tiff | gif.' => ' Formato del archivo jpg | jpeg | png | tiff | gif.',
  'A server error occurred, please try later' => '¡Huy! Un error de servidor. Inténtelo de nuevo más tarde',
  'A server error occurred. Try again later.' => '¡Huy! Un error de servidor. Inténtelo de nuevo más tarde.',
  'The image size is not more than 15 MB.' => 'Dimensión del imagen no más de 15MB.',
);
