<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Administrator will be removed' => '',
  'Become an expert' => '',
  'Expert will be removed' => '',
  'I agree to become an expert on the Internet platform {siteName}' => '',
  'I agree to join the project team on {siteName}' => '',
  'Not found' => 'No se encontró',
  'Permission granted to create my account and accept the rules of {tag}site{/tag}.' => '',
  'Please tell the author the reason why:' => '',
  'User will be deleted from the project' => '',
  'User will be removed' => '',
  'Want to join in the project {siteName} and develop the city along with all?' => '',
  'Why I don\'t want to join the team' => '',
  'Why I won\'t be an expert' => '',
  'Your refusal was sent to the author of the project.' => '',
  'Add' => 'Añadir',
  'Administrator' => 'Administador',
  'Confirm' => 'Confirmar',
  'Continue' => 'Continuar',
  'E-mail' => 'Correo electrónico',
  'E-mail or ID' => 'Correo electrónico o ID',
  'Expert' => 'Experta',
  'Expert opinion' => 'Opinión de experta',
  'Form your project`s team, attract experts and administrators' => 'Forme su equipo de proyecto y atraiga a expertos y administradores',
  'In the project' => 'En el proyecto',
  'Invitation{br /}sent' => 'La invitación{br /}se envió',
  'Invite' => 'Invitar',
  'Invited person`s name' => 'Nombre de la persona invitada',
  'Invited person`s surname' => 'Apelido de la persona invitada',
  'Join' => 'Juntarse',
  'Join project`s team on {siteName}' => 'Unirse al equipo del proyecto en {siteName}',
  'Name Surname' => 'Nombre Apellido',
  'No' => 'No',
  'Refuse' => 'Negarse',
  'Send' => 'Enviar',
  'Subscribe' => 'Suscribirse',
  'The invitation {br /} wasn`t accepted.' => 'La invitación {br /} no se aceptó.',
  'The page was not found' => 'La página no se encontró',
  'Unsubscribe' => 'Cancelar',
  'Yes' => 'Sí',
  'administrator' => 'administrador',
  'expert' => 'experta',
  'invite' => 'invitar',
  'press here to add an' => 'pulse para añadir un',
);
