<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'For authorities {tag} is a convenient tool of interaction with the citizens and feedback. {tag} involves citizens in social life and lets them participate in polls while assigning budget funds.' => 'Para las autoridades {tag} es un instrumento conveniente de interacción con los ciudadanos y de feedback. {tag} involucra a los ciudadnos en la vida pública y les permita participar en las votaciones durante la asignación de los fondos presupuestarios.',
  'If you have any questions or problems with the site, contact our helpdesk: ' => 'Si tiene algunos problemas o preguntas sobre el funcionamiento del sitio, póngase en contacto con nuestro servicio de apoyo técnico: ',
  'Thanks to {tag}, NGOs and public organizations get support from mass media, and the commercial organizations use {tag} for promoting brand’s social image and communicating with the audience.' => 'Gracias a {tag}, organizaciones públicas obtienen apoyo de PR de los medios, y el negocio usa {tag} para promover la imagen social de la marca y comunicarse con el auditorio.',
  'For cooperation, contact us: ' => 'Para los asuntos de cooperación, escríbanos a ',
  'What is ' => '¿Qué es ',
  ' is a local web project  offering user-friendly technologies of participation and interaction.' => ' – es una plataforma de internet local que ofrece tecnologías convenientes de participación e interacción. ',
  '{tag} lets the city’s activists involve a great number of people in different initiatives and find like-minded people. Our lawyers help to make appeals to authorities and control their execution. Also crowdfunding actions may be held on {tag}.' => '{tag} les permite a los activistas de la ciudad involucrar a mucha gente en diversas iniciativas y encontrar a correligionarios. Nuestros abogados ayudan a escribir solicitudes a las autoridades y controlan su execución. También se puede organizar acciones de micromezenazgo en {tag}.',
  'People living nearby and having similar interests use {tag} for solving common problems and making your city, area or yard better. Thanks to {tag} services, it is very easy to participate in the city’s life. You can change something just with one click without leaving your coach.' => 'La gente que vive cerca y tiene intereses parecidos, usa {tag} para solucionar problemas comunes y realizar ideas de mejora: en la ciudad, el barrio y el patio. Gracias a los servicios de {tag}, es muy fácil participar en la vida de la ciudad. Se puede cambiar algo en un clic sin levantarse del sofá.',
);
