<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Currently there are no events' => '',
  'Find and invite neighbors' => '',
  'Or join in order to be informed of the place' => '',
  'Add a photo' => 'Adjuntar una foto',
  'Add a rule' => 'Añadir una regla',
  'Add your life rule' => 'Añada su regla de vida',
  'An error has occurred.' => 'Un error ha ocurrido.',
  'An error has occurred. Image size not more than 15MB. The file extension jpg | jpeg | png | tiff | gif.' => 'Un error ocurrió. El archivo no debe ser más de 15Mb. El formato del archivo jpg | jpeg | png | tiff | gif.',
  'Become the first' => 'Hacerse el primero',
  'Invitation sent!' => 'La invitación se envió',
  'Join' => 'Juntarse',
  'Leave' => 'Dejar',
  'No residents yet' => 'Todavía no hay residentes',
  'No rules yet' => 'Todavía no hay reglas.',
  'Place’s rating' => 'Rating del lugar',
  'Something to share about this place?' => '¿Quiere contar algo sobre este lugar?',
  'Start typing the address of your home, workplace or school' => 'Empiece a escribir la dirección de su casa, lugar de trabajo o escuela',
  'There`s no photo.' => 'No hay ningún foto.',
  'add' => 'añadir',
  'change the address' => 'cambiar la dirección',
  'events' => 'eventos',
  'life rules' => 'reglas de vida',
  'photo' => 'foto',
  'residents' => 'residentes',
);
