<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Be a resident of the city' => '',
  'Become the Mayor ' => '',
  'He said its mayor | consider it the mayor ' => '',
  'Life around {br /} I ' => '',
  'Local control {br /} town ' => '',
  'Management at {br /} state ' => '',
  'My country ' => '',
  'People mayor ' => '',
  'Select the Mayor ' => '',
  'choose mayors | choose mayors' => '',
  'no ' => '',
  'select ' => '',
  'Log in' => 'Iniciar sesión',
  'My Page' => 'Mi página',
  'My city' => 'Mi ciudad',
  'Sign up' => 'Registrarse',
  'collected' => 'recogido',
  'out of' => 'de',
  'participant|participants|participants' => 'participante|participantes|participantes',
  'person|people|people' => 'persona|personas|personas',
);
