<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Confirmation code ' => '',
  'Confirmation email ' => '',
  'Confirmation number ' => '',
  'Correctly indicate your real name ' => '',
  'Correctly specify your real name ' => '',
  'Enter the new number, and we will send {br /} SMS with a confirmation code ' => '',
  'For you created your account with login {tag}{email}{/tag} Now you need to set a password: ' => '',
  'I accept {a}Terms of Service{/a} and confirm that I am 18 years old. ' => '',
  'In the life of the city you wish to {br /} affect the life of the city you {br /} indifferent? ' => '',
  'Login to members' => '',
  'Password to login ' => '',
  'Set password ' => '',
  'Sign in ' => '',
  'Support treatment ' => '',
  'Telling me about the success {siteName} ' => '',
  'The request has already been sent ' => '',
  'This number we will send {br /} SMS with a confirmation code ' => '',
  'Unable to authenticate via social network ' => '',
  'Verify later ' => '',
  'You have already sent a request to support this appeal. Check your e-mail for email with a link to confirm. ' => '',
  'Change the address' => 'Cambia la dirección',
  'Change the number' => 'Cambia el número',
  'Check your e-mail' => 'Chequea tu correo',
  'Confirm' => 'Confirmar',
  'Continue' => 'Continuar',
  'Done' => 'Hecho',
  'E-mail' => 'Correo electrónico',
  'I accept {tag}the terms of use{/tag}, agree with processing my personal data {br /}and confirm that I am 18.' => 'Acepto las {tag}condiciones de uso{/tag} y el tratamiento de mis datos personales.',
  'I accept {tag}the terms of use{/tag},{br /} agree with processing my personal data {br /}and confirm that I am 18.' => 'Acepto las {tag}condiciones de uso{/tag}{br /} y el tratamiento de mis datos personales.',
  'Mobile phone number' => 'Número de teléfono móvil',
  'Name' => 'Nombre',
  'Phone number' => 'número de teléfono',
  'Please, confirm the e-mail address' => 'Por favor, confirma la dirección de correo electrónico',
  'Registration' => 'Registro',
  'Save' => 'Guardar',
  'Send again' => 'Enviar de nuevo',
  'Sign up' => 'Registrarse',
  'Support' => 'Apoyar',
  'Surname' => 'Apellido',
  'We have sent a confirmation link to your email {email}{/tag}' => 'Te hemos enviado a tu dirección de correo electrónico {email}{/tag}un enlace al que deberás ir para obtener confirmación.',
  'We have sent a confirmation link to your email {tag}{email}{/tag}' => 'Te hemos enviamos a tu dirección de correo electrónico{tag}{email}{/tag} un enlace al que deberás ir para obtener confirmación.',
  'We`ve sent on the number {phoneNumber}{br /}a text message with the confirmation code' => 'Te hemos enviado al numero {phoneNumber}{br /}un SMS con el código de confirmación',
  'We’ll send you a link you’ll {br /} need to go for the confirmation' => 'Te enviaremos a un enlace{br /} al que deberás ir para obtener confirmación',
  'log in' => 'iniciar sesión',
);
