<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Error. Incorrect URL' => '',
  'Error. Please try again later' => '',
  'Incorrect document format' => '',
  'Incorrect image format' => '',
  'The maximum size limit is exceeded' => '',
  'Error. Host is not supported' => 'Error. El host no se mantiene.',
  'Incorrect format of the image. Choose a file no bigger than {size}, no more than {px} in width and height' => 'Formato incorrecto de imagen. Elija un archivo no más grande de {size}, hasta {px} de altura',
);
