<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'If you have any difficulties or questions, you can contact our support team ({support}) - you are sure to help! ' => '',
  'You offer to subscribe to geotag ' => '',
  'Hello, {tag}!' => '¡Buenos días, {tag}!',
  'Your {siteName}' => 'Su {siteName}',
  'find like-minded people to improve your city, neighbourhood, and courtyard together.' => 'encontrar a partidarios y junto a ellos mejorar su ciudad, barrio y patio.',
  'follow the most important events in places where you live, work and spend your free time' => 'estar al tanto de lo más importante en los lugares donde vive, trabaja y pasa su tiempo libre',
  'unite with your neighbours to solve your problems' => 'unirse con sus vecinos para solucionar problemas comunes',
  '{inviter} suggests you subscribe to geotag {link}. Why do it now?' => '{inviter} le ofrece suscribirse a la geoetiqueta {link}. ¿Por qué vale hacerlo ahora mismo?',
  '{siteName} develops services for people who live nearby and have common interests. By subscribing yourself to the geotag, you will be able to:' => '{siteName} desarrolla servicios para la gente que vive cerca y tiene intereses comunes. Suscribiéndose a la geoetiqueta, podrá:',
);
