<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Contacting authorities' => '',
  'Learn from the residents' => '',
  'Share news, idea, opinion or share issue' => '',
  'Sponsoring' => '',
  'Album' => 'Álbum',
  'Collecting signatures to solve the problem' => 'Recollectando firmas para solucionar el problema',
  'Copy the link and paste it here' => 'Copie el enlace y pégalo aquí',
  'Crowdfunding' => 'Crowdfunding',
  'Description' => 'Descripción',
  'End date' => 'Fecha de terminación',
  'Event' => 'Evento',
  'Event’s starting time' => 'Hora de inicio del evento',
  'Invite residents to participate' => 'Invitar a reseidentes a participar',
  'Is voting allowed?' => '¿Se puede votar?',
  'Issue' => 'Asunto',
  'Link' => 'Enlace',
  'Link to the source' => 'Enlace a la fuente',
  'Petition' => 'Solicitud',
  'Poll' => 'Votos',
  'Project name' => 'Nombre del proyecto',
  'Question' => 'Pregunta',
  'Source`s author' => 'Autor del fuente',
  'Source`s name' => 'Nombre del fuente',
  'Start date' => 'Fecha de inicio',
  'Title' => 'Título',
  'To' => '¿A quién se dirige?',
  'To the project on making the city better' => 'Proyecto de la mejora de la ciudad',
  'Total' => 'Suma',
  'more' => 'más',
);
