<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Public profiles' => 'Perfiles públicos',
  'All' => 'Todos',
  'Cities' => 'Ciudades',
  'E-mail' => 'Correo electrónico',
  'and organizations' => 'y organizaciones',
  '{siteName} doesn’t know this person yet.' => '{siteName} todavía no conoce a esta persona.',
  'You may invite him/her by e-mail.' => 'Puede invitarla por correo electrónico.',
  'Unfortunately, nothing was found. Try to search for something else.' => 'Desafortunadamente, no se encontró nada. Intente de buscar algo más.',
  'People' => 'Gente',
  'It is impossible to fulfill the search query. Try to simplify it or to search for something else.' => 'No se pudo analizar la consulta de búsqueda. Intente de simplificar la consulta o buscar algo más.',
  'Send an invitation' => 'Mandar la invitación',
  'Events' => 'Eventos',
  'Only ' => 'Solo ',
);
