<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Concerning the decision ' => '',
  'n==male# Decided | n# Decided to ' => '',
  'n==male# I myself decided this occasion | n# I myself decided this occasion ' => '',
  'n==male# Undecided | n# not decided ' => '',
  'n==male# considers that decided occasion. | n# considers that decided occasion. ' => '',
  'n==male# decided to excuse | n# decided pretext ' => '',
  'You can {tag}choose{/tag} another project to support.' => 'Puede elegir {tag}otra{/tag} acción para apoyarla.',
  'read&nbsp;more&nbsp;&#8594;' => 'leer&nbsp;más&nbsp;&#8594;',
);
