<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '10 minutes' => '',
  '24 hours' => '',
  '30 minutes' => '',
  '6 months' => '',
  'COMPANY INFORMATION' => '',
  'COOKIE' => '',
  'COOKIES POLICY' => '',
  'Cookies Disablement' => '',
  'DESCRIPTION' => '',
  'DISCLAIMER' => '',
  'DURATION' => '',
  'GENERAL CONDITIONS REGISTER' => '',
  'GOVERNING LAW AND JURISDICTION' => '',
  'INTELLECTUAL PROPERTY AND COPYRIGHT' => '',
  'In case the User wants to disable from its browser the aforesaid cookies, the instructions for the different browsers are the following:' => '',
  'In the event that any User considers that there are facts or circumstances revealing the illegality of the use of any content of the Website or websites accessible through the WebSite, including but not limited, to intellectual property infringement, publicity and image rights, private property or any other, such User shall send a notice to OpenSeneca (to Fax number +34 933 251 028 or to the email address legal@openseneca.com) which shall contain, at least, the following information: a) Personal data of the User notifying the infringement, address, telephone number and email address; and b) description of and information about the alleged infringing acts.' => '',
  'LINKS' => '',
  'Last revision: January 30th 2016' => '',
  'Legal Notice' => '',
  'MODIFICATIONS' => '',
  'Management of the languages used in the Website.' => '',
  'Notwithstanding the above, Users may browse the Website and its contents without restriction.
                Likewise, Users accept that the trademarks, trade names, logos and other distinctive signs contained in the Website are components whose ownership belongs to OpenSeneca or to third parties, which are protected by national laws and International Treaties on Intellectual Property. Unauthorized use or inappropriate use of such components may constitute an infringement of the intellectual property rights of SCYLT or those third parties.' => '',
  'OpenSeneca does not warrant the absence of interruptions and/or errors in the connection and/or Access to the Website and/or its contents whether belonging to OpenSeneca or to any third parties, neither the updating of the Website and/or such contents. OpenSeneca will use its best efforts to effect, in the shortest period of time, updates and corrections of errors and deficiencies, including those occurring in the access and/or connection to the Website and/or its contents.
                The Users are liable for the use of and access to the Website without prejudice of the legal actions that OpenSeneca and/or any third parties may start in case of illegal access to/ or inappropriate use of the Website and its contents, specifically in case of attack, suppression, elimination or destruction of the technological measures that, as the case may be, are protecting OpenSeneca’s contents or the contents of third parties.
                OpenSeneca shall not be liable for the presence of virus nor for security errors neither for the damages that may be caused to the devices of the Users or to the files or documents stored in such devices for the access and/or connection to the Website neither for the damages caused to third persons by means of illegal intromissions out of OpenSeneca control.
                OpenSeneca shall not be liable for the errors, omissions or inaccuracy of the information contained in this Website, which is provided “as is”.
                OpenSeneca shall neither be liable for the breach by the Users of the obligations they are accepting by accessing this Website which are contained in this Legal Notice and, in particular, shall not be liable for any infringement of the intellectual property rights, copyright, publicity rights and image rights, property rights or any other rights with regard to the goods and rights of any third person.' => '',
  'OpenSeneca may modify this Legal Notice and/or any other text of contractual nature of this Website without previous notice. Such modifications shall be effective seventy two (72) hours after having been posted herein.
                OpenSeneca may also terminate or suspend the rendering of the services contained in the Website and the Website service itself at any time, notwithstanding anything to the contrary set forth in any other text of contractual nature of this Website. Whenever is possible, OpenSeneca will warn/alert previously about such termination or suspension through this Website.' => '',
  'PRIVACY POLICY' => '',
  'PROCEDURE IN THE EVENT OF ILLEGAL ACTIVITIES' => '',
  'PROVIDER' => '',
  'PURPOSE' => '',
  'Persistent' => '',
  'TERMS AND CONDITIONS FOR THE ACCESS AND USE OF THE WEBSITE' => '',
  'Thanks for your attention' => '',
  'The contents, whether partial or in whole of this Website, and the Website itself as a visual presentation, including but not limited to logos, computer graphics, data, text, software, source code, database, images, sound and videos integrated in this Website are all elements belonging to OpenSeneca or licensed to OpenSeneca by third parties. Any and all of such elements are protected by the laws on Intellectual Property and/or Copyright and by the applicable International Conventions.
                It is forbidden, without prior written consent by OpenSeneca and/or by the right holders of the copyrights and/or the intellectual property and/or any other property right, as the case may be, to use and/or exploit the Website and/or its contents in any form, including but not limited to the following:' => '',
  'The owner of this Website is OpenSeneca S.A. (hereinafter referred to as OpenSeneca),
                with registered office at Pça. Gal.la Placídia, 1-3, 08006-Barcelona. OpenSeneca is registered in the Mercantile Register of Barcelona at Volume, XXX, Page XXXX, Sheet number XXX, inscription number XXX. OpenSeneca’s identification tax number is XXX. Users may contact OpenSeneca by telephone (+34 934 230 324), fax (+34 933 251 028) and email, at the address: info@openseneca.com OpenSeneca is the parent company of a companies’ group of different nationalities. Users may find contact details of each company of OpenSeneca’s group in info@openseneca.com.' => '',
  'The purpose of this Website is to provide general information to the public
                about OpenSeneca, its products and services. The purpose of the terms of use of this Legal Notice is
                to govern the permitted use of this Website whose URL is: <a href="http://www.openseneca.com" target="_blank">www.openseneca.com</a> and the
                 services
                 and/or contents hosted (hereinafter referred to as the Legal Notice and the Website, respectively) in accordance with the Law 34/2002 on Information Society Services and Electronic Commerce and other applicable legal provisions.' => '',
  'The terms and conditions of this Legal Notice and any other terms and conditions of this Website shall be governed by the laws of Spain.
                Disputes arising out from the access and use of this Website and its contents, and the interpretation and execution of these terms of use and any other term and condition of this Website shall be submitted to the Courts of the Users’ domicile, provided that the User resides in Spanish territory. In case the User, being an individual, resides abroad or the User is a legal entity which cannot be considered as User and/or Consumer according to law, the parties agree expressly to submit any dispute to the Courts of Barcelona (Spain).' => '',
  'These terms and conditions have been deposited in the General Conditions
                Register of the Register of Movable Goods of the Mercantile Register of Barcelona.' => '',
  'This Website makes available to the Users technical devices for linking (like, among others, links, banners, buttons) directories and searching tools which allow the Users the access to websites that belong or are managed by third parties (linked sites).
                The results from the searching tools are directly provided by third parties as a consequence of automatic mechanisms, so OpenSeneca cannot control and does not control such results. Users may start the procedure provided in condition 10 of this Legal Notice in order to request the cancellation of a link, in the event that they consider that in such linked sites an illegal activity is taking place and/or there is illegal information.
                In the event that third parties may want to establish a link to this Website, they may do so provided that, to the extent that is possible, the link is established to the home page of the Website; otherwise links may be established only if the URL of OpenSeneca is visible.' => '',
  'This Website permits anonymous navigation, therefore no registration is required and no personal data is requested.
                The only personal data that may be requested in this Website are those that the Users may declare when accessing to CONTACT section of this Website.
                In accordance with section 5 of the Organic Law 15/1999 of December 13th, on Personal Data Protection, OpenSeneca informs Users that their personal data are subject to automatized processing and stored in a filing system created by and for OpenSeneca, under its responsibility.
                This Users file is registered in the General Register of the Spanish Agency of Data Protection, according to the applicable law.
                Pursuant section 6 of the aforementioned Law on Personal Data Protection, Users may exercise their access, rectification, cancellation and opposition rights to the processing of their personal data (ARCO rights) before OpenSeneca by request sent by email to privacy@openseneca.com; or by post mail, addressing a signed letter to OpenSeneca Security Department, Pça. Gal.la Placídia, 1-3. 08006-Barcelona (Spain).
                The request shall contain the following details: name and surname of the Users, address for notices, copy of the DNI or passport, and the specific petition with regard to ARCO rights.
                OpenSeneca shall respect its secrecy and rightful treatment of the Users personal data obligations so as to impede the alteration, lost or non-authorized access to such personal data.
                OpenSeneca does not provide personal data to any third party.' => '',
  'This Website uses its own cookies and third parties’ cookies, either session or persistent cookies which are necessary for the performance of the Website or which have an analytical and statistical objective.
                    With regard to our own cookies OpenSeneca uses the strictly required ones in order to allow the User the navigation in this Website as well as using its essential functions.
                    OpenSeneca uses the analysis services of Google (<a href="https://support.google.com/analytics/answer/6004245" target="_blank">https://support.google.com/analytics/answer/6004245</a>) and LeadLander (<a href="http://www.leadlander.com/privacy.asp" target="_blank">http://www.leadlander.com/privacy.asp</a>). Both services use Javascript and cookies to help us to analyse the conduct of the Users of this Website and to gather statistical information. Cookies are small text files stored in your computer through the internet navigator.
                    Such cookies do not obtain personal information of the Users, but information regarding the number of Users accessing the Website, the number of pages that Users browse, frequency and repetition of the visits to the pages, its duration, the navigator used by the Users, the terminal or the city where the Users’ PI is allocated.
                    The objective is to collect information that helps OpenSeneca to provide a better and more technical service.' => '',
  'To allow Google Analytics’ service to collect anonymous statistics with regard the use of our Website, determining new sessions and repetitive visits to our Website.' => '',
  'To allow Google Analytics’ service to collect anonymous statistics with regard to the use of this Website. They are used to calculate new visits and recurrent visitors.' => '',
  'To allow Google Analytics’ service to collect anonymous statistics with regard to the web of origin which lead the user to our Website.' => '',
  'To allow Google Analytics’ services to collect anonymous statistics with regard to the use of our Website and the behaviour of the Users in order to measure the performance of our web.' => '',
  'To limit the speed of the service request, constraining the data collection in those website with massive traffic.' => '',
  'Types of cookies' => '',
  'Users are accepting the terms of use of this Legal Notice by accessing and using this Website. Users may download, store, reproduce and print a copy of this Legal Notice. The access to this Website is free. No application form is required for browsing the information and/or contents of this Website. Navigation through this Website is anonymous.' => '',
  'a) Any form of communication to the public, by any means, including the right of making available to the public, in such a way that any person may access the Website and/or the contents from a place and at a time individually chosen by them' => '',
  'b) Any form of distribution including but not limited to sale, rental or lending.' => '',
  'c) Any form of reproduction whether direct or indirect, temporary or permanent, by any means, whether total or partial, including but not limited to the reproductions for private use and the downloading in User’s devices.' => '',
  'd) Any form or transformation, whether total or partial.' => '',
  'session' => '',
);
