<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'After confirming your support, you will become a user of the system {tag}, and your opinion will be reflected on the page treatment and collective letters to be forwarded to the public authorities. ' => '',
  'Collective petition forwarded {department} ' => '',
  'Confirm treatment support ' => '',
  'E-Mail' => '',
  'For authorization in the system {tag} use the following login details: ' => '',
  'If more than 50 people support
// This appeal, <br>
// It will be formalized on the official form and sent by registered mail to the responsible person.' => '',
  'On {siteName} created an appeal based on {basement} "{title}" ' => '',
  'On {siteName} created based on the event {basement} "{title}" ' => '',
  'Posted collective treatment of citizens {recipient} ({department}) ' => '',
  'Your registration data in the system {siteName} ' => '',
  '{n} Sent a letter on the issue {subject} | {n} Sent letters to the problem {subject} | {n} Sent messages on the issue {subject} ' => '',
  'After the confirmation of your vote, you will be included in the list of people who voted for the importance of the topic and you will have the right to participate, with the author of the topic and other users, in editing the texts of collective letters that are formed within the framework of the issue.' => 'Después de la confirmación de tu Encuesta, se te incluirá en el número de usuarios que votaron por el tema y obtendrás el derecho de participar con el creado por del tema y otros usuarios en la correción de los textos de cartas colectivas que se formen en el marco de este asunto.',
  'After the confirmation of your vote, you will be included in the list of people who voted for the importance of the topic and you will have the right to participate, with the author of the topic and other users, in editing the texts of collective letters that are formed within the framework of the petition.' => 'Despues de la confirmación de tu Encuesta, se te incluirá en el número de usuarios que votaron por el tema y obtendrás el derecho de participar con el creado por del tema y otros usuarios en la correción de los textos de cartas colectivas que se formen en el marco de esta solicitud.',
  'An answer received {department}' => 'Una respuesta recibida {department}',
  'Ask your friends and acquaintances to support your appeal, and then their votes will be mentioned in the official letter' => 'Pide a tus amigos y conocidos a que apoyen tu solicitud, y así sus Encuestas se mostrarán en la carta oficial',
  'At the moment, the appeal has collected {signsCount} signatures. If more than 50 people support this appeal, we will print on an official form and send it to the organisation in charge by registered mail.' => 'En este momento la solicitud recolectó {signsCount} firmas.',
  'Based on' => 'Basado en',
  'If less than 50 people vote for this letter, you can put together a public appeal yourself, print it, sign it, and send it by mail. In this case, the letter will contain not only your opinion, but it will also show the votes of other citizens who voted for it.' => 'Si menos de 50 usuarios votan por este tema, también puede formalizar una carta pública, imprimirla y enviar el documento por correo. En este caso, la carta expresará no solo su opinión, sino mostrará los Encuestas de otros ciudadanos que la apoyaron.',
  'If less than 50 people vote for this subject, you can put together a public appeal yourself, print it, sign it, and send it by mail. In this case, the letter will contain not only your opinion, but it will also show the votes of other citizens who voted for it.' => 'Si menos de 50 usuarios votan por este tema, también puede formalizar una solicitud pública, imprimirla y enviar el documento por correo. En este caso, la carta expresará no solo su opinión, sino mostrará los Encuestas de otros ciudadanos que la apoyaron.',
  'If this message was sent to you by mistake and you don`t want to support the issue in question, please just ignore this message.' => 'Si recibió esta carta por equivocación y no quiere apoyar este asunto - solo ignore este mensaje.',
  'If this message was sent to you by mistake and you don`t want to support the petition in question, please just ignore this message.' => 'Si recibió esta carta por equivocación y no quiere apoyar esta solicitud - solo ignore este mensaje.',
  'Kind regards, ' => 'Atentamente, ',
  'Post the information about your appeal in social networks through the automatic publication buttons on the issue’s page' => 'Publicar la información sobre su solicitud en redes sociales a través del botón de publicación automática en la página del asunto',
  'See the page of the petition' => 'Ver la página de la solicitud',
  'Subscribe to ' => 'Suscríbete a la página de ',
  'To get the maximum support, you can:' => 'Para obtener el máximo apoyo, puedes:',
  'To make your vote count, please follow the link' => 'Para que tu Encuesta se acepte tienes que ir al enlace',
  'You (or, maybe, someone on your behalf) have supported the petition in the system' => 'Has apoyado (o probablemente alguien en tu nombre) la solicitud en el sistema',
  'Your appeal' => 'Tu solicitud',
  'Your appeal is published on {siteName}' => 'Tu solicitud se ha publicado en {siteName}',
  'an appeal has been created' => 'se ha creado una solicitud',
  'an event has been created' => 'se ha creado un evento',
  'is published' => 'se ha publicado',
  'recommends you, first of all, to attract the support of those who is interested in solving the problem like you.' => 'recomienda en primer lugar atraer al apoyo de los que están interesados en la solución del problema al igual que tú.',
);
