<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Address can not be edited and deleted, since an already formed' => '',
  'Address can not be edited, because it has supported' => '',
  'Letters' => '',
  'The city, where the organization ' => '',
  'Your passport details are pending. Please wait.' => '',
  'female' => '',
  'male' => '',
  'Are you sure you want to delete this content?' => '¿Estás seguto de que quieres eliminar este contenido?',
  'Asks' => 'Pregunta',
  'Author' => 'Creado por',
  'BUDGET' => 'PRESUPUESTO',
  'Budget' => 'Presupuesto',
  'Cancel' => 'Cancelar',
  'Citizen' => 'Ciudadano',
  'Copy' => 'Copiar',
  'Day' => 'Día',
  'Delete' => 'Eliminar',
  'Edit' => 'Editar',
  'Event' => 'Evento',
  'Guest' => 'Invitado',
  'Issue' => 'Asunto',
  'It may be the address of your home, your workplace or your children’s school.' => 'Puede ser tu domicilio, la dirección de tu lugar de trabajo o de la escuela de tus hijos.',
  'Link' => 'Enlace',
  'Local' => 'Local',
  'Mark the places you care about. You’ll receive notifications about the events and the news from these places.' => 'Indica los lugares que te interesan. Recibirás notificaciones sobre los eventos y las noticias de estos lugares.',
  'Month' => 'Mes',
  'Nobody' => 'Nadie',
  'Organizator' => 'Organizador',
  'Personal Information' => 'Datos personales',
  'Petition' => 'Solicitud',
  'Poll' => 'Encuesta',
  'Project' => 'Proyecto',
  'Registration Information' => 'Datos de registro',
  'Reports' => 'Informes',
  'TO:' => 'LA SOLICITUD ESTÁ DIRIGIDA A:',
  'What will the money be spent on?' => '¿En qué se gastará el dinero?',
  'Year' => 'Año',
  'You can`t edit the poll because people have already voted.' => 'No se permite la edición de una encuesta que contiene votos',
  'You participate in the life of' => '¿Es ésta tu ciudad?',
  'project on making the city better' => 'proyecto de la mejora de la ciudad',
);
