<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' - A framework for action ' => '',
  ' He helped the sports festival "Life Energy" to negotiate with the park Northern Tushino, where the event was the result. ' => '',
  ' in different cities of Russia. ' => '',
  ' indifferent resident who helped buy the materials for the shares at the painting ' => '',
  ' information on the collection of funds for the rescue of the monument of constructivism White Tower in Ekaterinburg, representatives of the portal ura.ru donated the missing funds. ' => '',
  ' it finalize and send the desired destination. A well-composed handling increases the chances of success. ' => '',
  ' money to buy a used / have a bike in Mozhaisk children`s center.' => '',
  ' protected from markups and their results can be the basis for a constructive dialogue with the authorities and public organizations. ' => '',
  '- A platform for the realization of your good ideas into practice.' => '',
  'Addressed: ' => '',
  'An expert in the field of transport in Anton Buslov prepare prisoners for the user on the tram rails in Krasnoyarsk.' => '',
  'Any idea how to make the city better? Tell us about it on ' => '',
  'Are you an active resident of the city, and are ready to participate in improving it? Find out what you will be useful to ' => '',
  'Children`s porches Project found on ' => '',
  'Discuss with the experts and get support from other people. Together you more.' => '',
  'Find like-minded ' => '',
  'Get solutions. Write to appeal to the authorities and collect the signatures of other users. Lawyers' => '',
  'Helping to become public: welcome to speak at the event are included in the digest of interesting projects, nominating for awards' => '',
  'Here are examples of initiatives that received support ' => '',
  'I accept the ' => '',
  'Kaliningrad Association of young people with disabilities "Apparel" found a volunteer designer to create a new version of its website. ' => '',
  'Obtain financial support from other users. Many ideas can be implemented by forces and means of the townspeople themselves, support your initiative.' => '',
  'Our services help you to act more quickly and effectively. Spend a vote and find out the opinion of neighbors about his idea. Collect signatures on a petition to the authorities. Tell us what you can to help others, {br /} and get support. Make your socially useful project together with us. ' => '',
  'Platform actions' => '',
  'Polls and voting' => '',
  'Promising ideas receive special support ' => '',
  'Read the opinions of others about your initiative. The vote on ' => '',
  'Receipt ' => '',
  'Redirects' => '',
  'Replies' => '',
  'Seeing on ' => '',
  'Signatures: ' => '',
  'Successful projects' => '',
  'Support initiatives' => '',
  'Terms of Service {/a}, give my consent to the processing of personal data and confirm that I am 18 years old.' => '',
  'The collection of signatures' => '',
  'Tools of the active citizen ' => '',
  'Upload a picture ... ' => '',
  'User gathered on ' => '',
  'We are helping to prepare good promotional materials: we prompt the idea of ​​advertising, together create design layouts, shoot a video of the project ' => '',
  'We are helping with the PR: attract media attention to your initiative.' => '',
  'We are helping with the expert opinion: attract people who have already implemented similar projects and can share the experience.' => '',
  'We help to find the correct contact: familiar with other projects and organizations that can become your partners' => '',
  'active city dweller ' => '',
  'and are ready to participate in improving it? Do you know how to landscape your yard, you want to make a holiday to its neighbors or to propose the initiative to the city authorities? ' => '',
  'An answer received:' => 'Una respuesta recibida:',
  'Answer' => 'Respuesta',
  'Petition' => 'Solicitud',
  'Appeals' => 'Solicitudes',
  'Are you sure you want to delete this image?' => '¿Está seguro que quiere eliminar esta imagen?',
  'Create' => 'Crear',
  'Crowdfunding' => 'Crowdfunding',
  'Date:' => 'Fecha:',
  'E-mail' => 'Correo electrónico',
  'Notification of redirection' => 'Notificación de redirección',
  'Redirected:' => 'Redirigido A:',
  'Sent ' => 'Enviado ',
  'Sign up' => 'Registrarse',
  'cancel' => 'cancelar',
  'delete' => 'eliminar',
  'or' => 'o',
  'save' => 'guardar',
);
