<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Failed to save voice ' => '',
  'Invalid code or the name ' => '',
  'Invalid start or end of voting ' => '',
  'The album is not found ' => '',
  'This code of your ballot is not received' => '',
  'Unable to save the papers' => '',
  'Voting has ended ' => '',
  'Voting has not yet started ' => '',
  'We did not find such a candidate ' => '',
  'We did not find such a voice ' => '',
  'We did not find this newsletter ' => '',
  'We found such a partner ' => '',
  'We have not found such a project ' => '',
  'You can not change the project ' => '',
  'You can not create new projects' => '',
  'You can not edit the project ' => '',
  'You can not vote in the project' => '',
  'You can not vote without specifying the names in the profile ' => '',
  'You must specify project identifier' => '',
  'You must specify the steps of the project ' => '',
);
